name: CI

on: [push, pull_request]

jobs:
  test:
    name: Test
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Build
      env:
        GOPATH: /home/runner/work/
      run: cd functions/saba_disambiguator && go build -o build/saba_disambiguator main.go
